### ISSUE TITLE
About a new button

### ISSUE THREAD

**Issue by kys00514** [kys00514/i-want-to-graduate#7]
How about we make a new button in which the user can indicate the he/she is done with inputting the grades? I would like to know your opinions. #5

**Comment by magma0409** [comment]
What function does it serve?

**Comment by cardioman** [comment]
I like the idea. The button could avoid making users getting confused when they are entering their grades.

**Comment by kys00514** [comment]
To magma0409: It calculates the grades and shows it in the final graph.

**Comment by magma0409** [comment]
Oh that would be better
